In [11]:
import torch
import numpy as np

In [8]:
t = torch.ones((3,3))
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
mat = torch.randn((5,5))
print(mat)

tensor([[ 1.1437,  0.9409,  0.9248,  0.5202,  0.2434],
        [-0.6436,  1.2776, -1.0562,  1.0390, -0.8900],
        [-0.8379,  0.9047, -0.2579,  0.7858, -0.1232],
        [ 0.4156, -0.2878, -0.1948, -2.5244, -0.3555],
        [-2.0021, -0.0298, -0.4851, -1.2413, -0.8475]])


In [14]:
print(mat.max())
print(mat.argmax())

tensor(1.2776)
tensor(6)


In [3]:
arr = torch.rand(9)
print(arr)
mat2 = arr.reshape((3,3))
print(mat2)

tensor([0.6090, 0.1813, 0.8748, 0.1882, 0.8983, 0.7058, 0.0144, 0.8609, 0.0687])
tensor([[0.6090, 0.1813, 0.8748],
        [0.1882, 0.8983, 0.7058],
        [0.0144, 0.8609, 0.0687]])


In [5]:
x = torch.empty(4,4)
print(x)

tensor([[9.7688e+00, 4.5810e-41, 9.7688e+00, 4.5810e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [8]:
a = torch.rand(3,3)
b = torch.rand(3,3)
print(a)
print(b)
print(torch.add(a,b))

tensor([[0.6308, 0.8270, 0.1518],
        [0.5017, 0.6838, 0.0835],
        [0.3372, 0.9136, 0.2142]])
tensor([[0.2316, 0.5421, 0.1324],
        [0.7455, 0.8268, 0.4917],
        [0.7299, 0.6139, 0.7893]])
tensor([[0.8623, 1.3691, 0.2842],
        [1.2472, 1.5106, 0.5752],
        [1.0671, 1.5275, 1.0034]])


In [10]:
c = a.numpy()
print(c)

[[0.6307731  0.8269601  0.15178454]
 [0.50172424 0.68378633 0.0835402 ]
 [0.3371696  0.91360873 0.21417981]]


In [14]:
a1 = np.ones((4,4))
print(a1)
a2 = torch.from_numpy(a1) 
print(a2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
