In [23]:
import torch

In [24]:
x = torch.ones(3,3,requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [25]:
y = x+2
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [26]:
print(y.grad_fn)

In [27]:
z = y*y+1
print(z)
out = z.mean()
print(out)

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]], grad_fn=<AddBackward0>)
tensor(10., grad_fn=<MeanBackward0>)


In [28]:
a = torch.rand(3,3)
print(a)
print(a.requires_grad)

tensor([[0.3230, 0.3773, 0.6468],
        [0.4741, 0.2714, 0.0563],
        [0.3615, 0.9493, 0.2133]])
False


In [29]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [30]:
b=a*a
print(b)
print(b.grad_fn)

tensor([[0.1043, 0.1423, 0.4184],
        [0.2248, 0.0737, 0.0032],
        [0.1307, 0.9012, 0.0455]], grad_fn=<MulBackward0>)


In [31]:
out.backward()

In [32]:
print(x.grad)

tensor([[0.6667, 0.6667, 0.6667],
        [0.6667, 0.6667, 0.6667],
        [0.6667, 0.6667, 0.6667]])


In [33]:
x1 = torch.randn(3, requires_grad=True)
y1 = x1 * 2
while y1.data.norm() < 1000:
    y1 = y1 * 2
print(y1)

tensor([  581.6132,   237.2218, -1473.5990], grad_fn=<MulBackward0>)
